# ============================================================================
# STEP 4: Strip Function to Condition-Relevant Code Only
# ============================================================================
# Purpose:
#   - Read the raw function generated by Step 03.
#   - Re-extract the function from source when Step 03 output is unavailable.
#   - Keep control flow and assignments that feed later conditions.
#   - Save the result to:
#       <WorkDir>\testObjectCode\<TestObject>_conditions.c
#
# Configuration is loaded by common.ps1.
# ============================================================================

. (Join-Path $PSScriptRoot "..\helpers\common.ps1")

$STEP       = "STEP4"
$TestObject = $Config.TestObjects
$Module     = $Config.Module
$SourceDir  = $Config.SourceDir
$WorkingDir = $Config.WorkDir

Show-Banner "STEP 4 : STRIP FUNCTION TO CONDITION-RELEVANT CODE"
Write-StepStart $STEP

Write-Info -Step $STEP -Message "Test Object: $TestObject"
Write-Info -Step $STEP -Message "Module: $Module"

$result = Export-TestObjectConditionCode `
    -Step $STEP `
    -TestObject $TestObject `
    -Module $Module `
    -SourceDir $SourceDir `
    -WorkingDir $WorkingDir

Write-Info -Step $STEP -Message "Raw function source: $($result.InputFile)"
Write-Info -Step $STEP -Message "Condition source saved: $($result.OutputFile)"

Write-Host ""
Write-Host "Condition-relevant content:" -ForegroundColor Cyan
Write-Host ("-" * 80) -ForegroundColor Gray
Write-Host $result.Content
Write-Host ("-" * 80) -ForegroundColor Gray

Write-StepEnd $STEP

Write-Host ""
Write-Host ("=" * 80) -ForegroundColor Cyan
Write-Host "STEP 4 COMPLETE" -ForegroundColor Cyan
Write-Host "Next-> Run step5: resolve defines" -ForegroundColor Cyan
Write-Host ("=" * 80) -ForegroundColor Cyan

exit 0
